version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  railsdocker:
    image: kevinponce/rails_docker
    container_name: railsdocker
    restart: always
    ports:
      - "3001:3000"
    labels:
      # https://github.com/kubernetes/kompose/blob/master/docs/user-guide.md#labels
      kompose.service.type: loadbalancer # nodeport
      kompose.service.nodeport.port: 30000
    depends_on:
      - db