version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  railsdocker:
    # image: kevinponce/rails_docker
    # container_name: railsdocker
    build: .
    restart: always
    ports:
      - "3001:3000"
    environment:
      - TEST=me
    labels:
      # https://github.com/kubernetes/kompose/blob/master/docs/user-guide.md#labels
      kompose.service.type: nodeport
      kompose.service.nodeport.port: 30000
    depends_on:
      - db
      - dynamodb