apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o .kubernetes/ -f docker-compose.yml
    kompose.service.nodeport.port: "30000"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: railsdocker
  name: railsdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: railsdocker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o .kubernetes/ -f docker-compose.yml
        kompose.service.nodeport.port: "30000"
        kompose.service.type: nodeport
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: railsdocker
    spec:
      containers:
        - image: kevinponce/rails_docker
          name: railsdocker
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
