apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: |
    - userarn: arn:aws:iam::***:user/railsDockerGitHubAction
      username: railsDockerGitHubAction
      groups:
        - system:masters