name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.name }}"
        echo "Log level: ${{ github.event.inputs.home }}"
    - name: Webhook
      uses: fjogeleit/http-request-action@v1
      with:
          url: 'https://157b-47-222-59-146.ngrok-free.app/webhooks/github_action'
          method: 'GET'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
