name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      creative_draft_id:
        description: 'Creative Draft ID'
        required: true
      data:
        description: 'Stringified JSON Data'
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.creative_draft_id }}"
        echo "Log level: ${{ github.event.inputs.data }}"
    - name: Webhook
      uses: fjogeleit/http-request-action@v1
      with:
          url: 'https://99da-47-220-63-33.ngrok-free.app/webhooks/github_actions/test_creative_draft_results'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "creative_draft_id": "${{ github.event.inputs.creative_draft_id }}", "status": "pass", "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
