name: Simple Shell
# on: [push]
on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multline script
        run: |
          node -v
          npm -v